### ISSUE TITLE
Game crashed in 1.16.4

### ISSUE THREAD

**Issue by linzexin022** [raltsmc/desolation#4]
Minecraft version: 1.16.4
Fabric Loader version: 0.10.8
Fabric API version: 0.26.3
GeckoLib version: 3.0.0+beta.7 
Desolation version: 1.0.2.1-beta

Here's the crash text:
[crash-2020-11-25_17.28.40-client.txt](https://github.com/raltsmc/desolation/files/5595683/crash-2020-11-25_17.28.40-client.txt)

**Comment by linzexin022** [comment]
Although this may be bothering you, I sincerely hope you can update it to be compatible with the latest version of fabric API. I like the idea of this mod very much!

**Comment by raltsmc** [comment]
Hey, it looks like the issue is being caused by Geckolib - the mod uses version 2.0.0, not 3.0.0. Sorry for the confusion, I'll add a notice to the Curseforge page. I just tested it with the versions you listed and it works fine with Geckolib 2.0.0. Try downgrading and let me know if it still crashes!

**Comment by linzexin022** [comment]
aha, it works! Thank you!
